// <auto-generated />
using System;
using anBlogg.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace anBlogg.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20200429084922_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("anBlogg.Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("591d79d0-7742-4f9d-b285-c30319036ec0"),
                            AccountId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Juri",
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0a6c5317-a564-4e48-8e79-df271e9e72d3"),
                            AccountId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Vanessa",
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("184edd78-aeab-4c20-becc-6d3dc9f1b841"),
                            AccountId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Matthew",
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("anBlogg.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b56a3616-6b3f-4e78-aae1-04ca960c1a54"),
                            AuthorId = new Guid("184edd78-aeab-4c20-becc-6d3dc9f1b841"),
                            Contents = "<p>My first comment! :D</p>",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = new Guid("3eabbb2c-4bbd-4863-9392-674b28aa7dcb"),
                            Score = 0
                        },
                        new
                        {
                            Id = new Guid("0fac4488-8943-11ea-bc55-0242ac130003"),
                            AuthorId = new Guid("591d79d0-7742-4f9d-b285-c30319036ec0"),
                            Contents = "<p>Nice work Vanessa !!!</p>",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = new Guid("3eabbb2c-4bbd-4863-9392-674b28aa7dcb"),
                            Score = 0
                        });
                });

            modelBuilder.Entity("anBlogg.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("991861b0-e24f-40d9-88f4-8567de578668"),
                            AuthorId = new Guid("591d79d0-7742-4f9d-b285-c30319036ec0"),
                            Contents = @"<p>Donec nec nisi egestas, mollis orci quis, sodales est. Fusce sed luctus diam. 
                    Sed posuere egestas arcu, vitae iaculis enim pulvinar vitae. Praesent efficitur purus nisi, 
                    vitae feugiat erat faucibus et. Donec vitae magna eu ipsum dictum dignissim aliquet sodales arcu. 
                    Sed eu ex auctor, condimentum ex ut, aliquam lectus. Praesent sollicitudin nibh vitae erat aliquet 
                    aliquet. Duis porta pharetra augue, commodo lobortis ligula placerat ut. Vivamus auctor facilisis 
                    felis vitae consequat. Vivamus dui sem, rhoncus nec condimentum id, porta ac velit. Donec pulvinar, 
                    diam quis ultricies pellentesque, purus ligula lobortis ipsum, quis consectetur erat diam sodales urna. 
                    Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. 
                    Maecenas elit eros, pretium eget dui et, tristique ornare ex.</p>",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 0,
                            Title = "PiS is destroying Poland?"
                        },
                        new
                        {
                            Id = new Guid("1c499376-e8e3-41e9-b545-8a26d1fee602"),
                            AuthorId = new Guid("591d79d0-7742-4f9d-b285-c30319036ec0"),
                            Contents = @"<p>Donec nec nisi egestas, mollis orci quis, sodales est. Fusce sed luctus diam. 
                    Sed posuere egestas arcu, vitae iaculis enim pulvinar vitae. Praesent efficitur purus nisi, 
                    vitae feugiat erat faucibus et.</p>",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 0,
                            Title = "Opposition is defensing the law?"
                        },
                        new
                        {
                            Id = new Guid("3eabbb2c-4bbd-4863-9392-674b28aa7dcb"),
                            AuthorId = new Guid("0a6c5317-a564-4e48-8e79-df271e9e72d3"),
                            Contents = @"<p>Donec nec nisi egestas, mollis orci quis, sodales est. Fusce sed luctus diam. 
                    Sed posuere egestas arcu, vitae iaculis enim pulvinar vitae. Praesent efficitur purus nisi, 
                    vitae feugiat erat faucibus et.</p>",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 0,
                            Title = "What after Corona?"
                        },
                        new
                        {
                            Id = new Guid("809971e5-e6d1-4d4a-8bf3-959411ecd2f7"),
                            AuthorId = new Guid("184edd78-aeab-4c20-becc-6d3dc9f1b841"),
                            Contents = @"<p> Vivamus auctor facilisis Praesent efficitur purus nisi vitae iaculis enim pulvinar vitae.
                    felis vitae consequat. Vivamus dui sem, rhoncus nec condimentum id, porta ac velit. Donec pulvinar, 
                    diam quis ultricies pellentesque, purus ligula lobortis ipsum, quis consectetur erat diam sodales urna. 
                    Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. 
                    Maecenas elit eros, pretium eget dui et, tristique ornare ex.</p>",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 0,
                            Title = "Kebab officially the best food in the world!"
                        });
                });

            modelBuilder.Entity("anBlogg.Domain.Entities.Comment", b =>
                {
                    b.HasOne("anBlogg.Domain.Entities.Author", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("anBlogg.Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("anBlogg.Domain.Entities.Post", b =>
                {
                    b.HasOne("anBlogg.Domain.Entities.Author", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("anBlogg.Domain.ValueObjects.Tags", "Tags", b1 =>
                        {
                            b1.Property<Guid>("PostId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Raw")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PostId");

                            b1.ToTable("Posts");

                            b1.WithOwner()
                                .HasForeignKey("PostId");

                            b1.HasData(
                                new
                                {
                                    PostId = new Guid("991861b0-e24f-40d9-88f4-8567de578668"),
                                    Raw = "<tag><other-tag>"
                                },
                                new
                                {
                                    PostId = new Guid("1c499376-e8e3-41e9-b545-8a26d1fee602"),
                                    Raw = "<tag><some-other-tag>"
                                },
                                new
                                {
                                    PostId = new Guid("3eabbb2c-4bbd-4863-9392-674b28aa7dcb"),
                                    Raw = "<tag><other-tag>"
                                },
                                new
                                {
                                    PostId = new Guid("809971e5-e6d1-4d4a-8bf3-959411ecd2f7"),
                                    Raw = "<tag><completely-other-tag>"
                                });
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
